DROP TABLE IF EXISTS `actor`;

CREATE TABLE IF NOT EXISTS `actor`
(
    id BIGINT NOT NULL COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    born DATE NULL DEFAULT NULL COMMENT '出生日期',
    PRIMARY KEY (id)
);


DROP TABLE IF EXISTS `movie`;

CREATE TABLE IF NOT EXISTS `movie`
(
    id BIGINT NOT NULL COMMENT '主键ID',
    title VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
    PRIMARY KEY (id)
    );