server:
  port: 8080

spring:
  application:
    name: spider-media
  profiles:
    include: h2,es
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
